### ISSUE TITLE
Downloading Lomb-Scargle statistics

### ISSUE THREAD

**Issue by sjoerdopdam** [itmat/circadb#10]
Hello,

I would like to get the Lomb-Scargle statistics (phase,period, q-value, p-value) when I download, is there any way to do this ? (right now only the JTK statistics are downloaded).

Best,
Sjoerd

**Comment by khayer** [comment]
You can now download the Lomb-Scargle statistics by setting the "probability filter" to either "Lomb Scargle P-value" or "Lomb Scargle Q-value".
