### ISSUE TITLE
Missing data for download

### ISSUE THREAD

**Issue by wgpembroke** [itmat/circadb#11]
Hi,

The Panda 2002 SCN datasets are missing samples from CT46 in the .csv files (but show on the graph viewer). Could you please reupload the files with these samples included.

Many thanks,
Will

**Comment by khayer** [comment]
Hi Will,

could you tell me exactly what query and options you used? I made a few changes this morning and now I am having trouble replicating the issue you posted.

Best,
K

**Comment by wgpembroke** [comment]
http://circadb.hogeneschlab.org/about

Scroll down to  Mouse SCN MAS4 Panda 2002 & Mouse SCN gcrma Panda 2002

Click download data.

The resultant csv files are missing timepoints "CT46" - check the column names.

Thanks,
Will

**Comment by hogenesch** [comment]
The data isn't missing, that sample failed -- the SCN is only 10,000 cells, so it's hard to dissect. 

Best,

John Hogenesch

**Comment by wgpembroke** [comment]
Thanks John, that's a shame

May I ask how the data point at CT46 is visible on the graph viewer for this dataset. Eg. Per2
![per2_scn](https://cloud.githubusercontent.com/assets/13603209/10141151/d774d034-6602-11e5-9311-4e0e286402f0.png)

Will

**Comment by hogenesch** [comment]
I think it's a rolling average of nearby points for visualization purposes. It is not included in the analyses. 

You know there's a more recent dataset with 24 points plus RNA-seq, right? The Mouse 1.0ST SCN 2014 data.

![image](https://cloud.githubusercontent.com/assets/334055/10141648/b6ee515e-65db-11e5-8966-efd3506af9b5.png)

**Comment by wgpembroke** [comment]
Ah no I didn't.
I guess it's currently unpublished - so the csv and raw files will be available when it is.

Thanks,
Will

**Comment by hogenesch** [comment]
The CSV data is already up at circadb.hogeneschlab.org. We've submitted the data to GEO but it isn't up yet. The paper's in preparation for submission. 

Cerebellum, whole hypothalamus, and brain stem are also there.

**Comment by wgpembroke** [comment]
great, cheers!
