### ISSUE TITLE
special characters in gene list

### ISSUE THREAD

**Issue by KaBrrrp** [itmat/circadb#12]
Apparently when submitting a gene list with special characters such as '.' or '-' only the last gene of the list containing a special character is searched and all other genes are ignored.

for example try searching
Cry1
Cry2
Per2
Per3
-> returns 95 hits

then searching
Per2
Per3
Epb4.1l1
Epb4.1
Cry1
Cry2
-> returns 4 hits (all Epb4.1)

Best,
Kolja

**Comment by khayer** [comment]
Thank you for reporting the issue. The search now returns the correct number of results. 

-K
