### ISSUE TITLE
JTK Cycle version

### ISSUE THREAD

**Issue by ghisbreton** [itmat/circadb#9]
Hi
Is the version of JTK_Cycle used on CircaDB the same as the one used for the Zhang et al 2014 PNAS paper? I was trying to see the list of cycling genes in the adrenal gland with a q-value of 0.05 and the total is 558 while in the paper according to Fig 1A, it should be slightly over 1000. It looks like the ranking between organ is very similar to Zhang but the total count for every organ is very different. And the number of 558 includes a wide period range which in the paper is suppose to list only oscillating genes with a period of 24. Thanks for the help.
Ghislain

**Comment by khayer** [comment]
Hi,
the Zhang et al 2014 PNAS paper only uses a subset of the probesets analyzed in CircaDB (quoted from the Method section):

> Probesets on the Affymetrix MoGene 1.0 ST array were cross-referenced to best-matching gene symbols by using Ensembl BioMart software, then filtered for known protein-coding status. The resulting 19,788 genes formed the protein-coding background set.

In contrast on CircaDB we analyzed all 35,556 probesets without any filtering. So here there is a larger input to the multiple testing correction and thus the q-values differ.

**Comment by ghisbreton** [comment]
Thanks for the quick reply. Highly appreciated. If Zhang is using a subset, they should be getting less hits than CircaDB. They get around a 1000 for adrenal gland and I can get only 558 on CircaDB (JTK q value of 0.005).

**Comment by ghisbreton** [comment]
OK. I just re-read your answer more carefully. I get it. Thank you again.

**Comment by khayer** [comment]
You're welcome! Let us know if there is anything else.
